name: Stage Azure deploy

on:
  push:
    branches:
      - SIN-197-CI-CD-woo 
      - CI-CD-workflow

env: 
  BACKEND_ENVIRONMENT_STAGE: ${{vars.BACKEND_ENVIRONMENT_STAGE}}
  APP_VERSION_PREFIX_STAGE: ${{vars.APP_VERSION_PREFIX_STAGE}}
  AZURE_STORAGE_ACCOUNT_STAGE: ${{vars.AZURE_STORAGE_ACCOUNT_STAGE}}
  AZURE_STORAGE_CONTAINER_NAME_WOO_STAGE: ${{vars.AZURE_STORAGE_CONTAINER_NAME_WOO_STAGE}}
  AZURE_CREDENTIALS: ${{vars.AZURE_CREDENTIALS}}
jobs:
  build:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  build-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Append version to file
      run: echo $(jq -r '.version' package.json) >> something.txt

    - name: Replace string in simplyin.php
      run: |
        sed -i '13s/.*/  * Version:           $(jq -r '.version' package.json) /' simplyin.php


    - name: Replace string in simplyin.php
      run: |
        sed -i '12s/.*/ * Description: SimplyIN application description. ${{ env.APP_VERSION_PREFIX_STAGE }} /' simplyin.php
        

    - name: Dependencies install 
      run: |
        cd public
        yarn install

    - name: Create react app bundle 
      run: |
        cd public
        yarn deploy-build
    
    - name: Remove node_modules
      run: |
        rm -rf logs
        rm -rf .git
        rm -rf .github
        cd public
        rm -rf src
        rm -rf node_modules

    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: simplyin-woo-stage
        path: .

  create-zip-file:
    runs-on: ubuntu-latest
    needs: [build-app]

    steps:
    - name: Download files
      uses: actions/download-artifact@v2
      with:
        name: simplyin-woo-stage
        path: .

    - name: Zip files
      run: |
        zip -r simplyin-woo-stage.zip .

  deploy-zip-file-in-azure:
    runs-on: ubuntu-latest
    needs: [create-zip-file]

    steps:
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
    
    - name: Upload files to Azure Storage
      run: |
        az storage blob upload-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT_STAGE }} --destination ${{ env.AZURE_STORAGE_CONTAINER_NAME_WOO_STAGE }} --source . --pattern "*.zip"