name: Stage Azure deploy

on:
  push:
    branches:
      - SIN-197-CI-CD-woo 

env: 
  ENV: "stage"
jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dependencies install 
      run: |
        cd public
        yarn install

    - name: Create react app bundle 
      run: |
        cd public
        yarn deploy-build
    
    - name: Remove node_modules
      run: |
        rm -rf logs
        cd public
        rm -rf node_modules
        rm -rf src

  create-zip-file:
    needs: [build-app]
    steps:
    - name: Zip files
      run: |
        zip -r simplyin-woo-stage.zip .
        # This will zip the entire current directory
        
  deploy-zip-file-in-azure:
    needs: [create-zip-file]
    steps:
   - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      

